remote_theme: just-the-docs/just-the-docs
domain: xgmqzs.khboys.cn
url: https://xgmqzs.khboys.cn
color_scheme: dark
aux_links:
  "GitHub":
    - "https://github.com/When-Xiangge-Cry/Story"
  "官网":
    - "https://club.khboys.cn"
nav_external_links:
  - title: Discussions讨论
    url: https://github.com/When-Xiangge-Cry/Story/discussions
    hide_icon: false
  - title: issues问题
    url: https://github.com/When-Xiangge-Cry/Story/issues
    hide_icon: false
